### ISSUE TITLE
Add `Cypress` as End-to-end Testing framework

### ISSUE THREAD

**Issue by bartvdbraak** [bartvdbraak/omnidash#20]

**Comment by bartvdbraak** [comment]
```
      - name: Cypress run
        uses: cypress-io/github-action@v2
        env:
          CYPRESS_BASE_URL: ${{ github.event.deployment_status.target_url }}
```
